# fly.toml app configuration file generated for vortex-snowgear on 2024-02-17T10:24:18-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vortex-snowgear'
primary_region = 'ord'

[env]
  ASPNETCORE_URLS="http://+:8080"

[build]
  image = 'nomad1135/restore'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
